runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /static
  static_dir: static

- url: /stylesheets
  static_dir: stylesheets

- url: /css
  static_dir: css
- url: /assets
  static_dir: assets

- url: /.*
  script: main.app
- url: /.*
  script: trending.app

- url: /create_stream
  script: main.app
  login: required

# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: PIL
  version: latest
# [END libraries]
